// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Dose struct {
	ID        string
	RegimenID string
	Refill    int64
	Time      int64
	Amount    float64
	Unit      string
	Taken     sql.NullBool
	TimeTaken sql.NullInt64
}

type Medication struct {
	ID      string
	Name    string
	Generic bool
	Brand   string
}

type Prescription struct {
	ID             string
	MedicationID   string
	Schedule       []byte
	ScheduledStart sql.NullInt64
	Refills        int64
	Doses          int64
	Patient        string
}

type Regimen struct {
	ID             string
	MedicationID   string
	Patient        string
	PrescriptionID string
}

type User struct {
	ID       string
	Approved bool
}
