// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Dose struct {
	ID        string
	RegimenID string
	Time      int64
	Amount    int64
	Unit      string
	Taken     sql.NullBool
	TimeTaken sql.NullInt64
}

type Medication struct {
	ID      string
	Name    string
	Generic bool
	Brand   string
}

type Prescription struct {
	ID             string
	MedicationID   string
	Schedule       []byte
	ScheduledStart sql.NullInt64
	Refills        int64
	Doses          int64
}

type Regimen struct {
	ID           string
	MedicationID string
	Patient      string
}

type User struct {
	ID   string
	Name string
}
