// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDose = `-- name: CreateDose :one
INSERT INTO
    doses (id, regimen_id, refill, time, amount, unit)
VALUES
    (?, ?, ?, ?, ?, ?) RETURNING id, regimen_id, refill, time, amount, unit, taken, time_taken
`

type CreateDoseParams struct {
	ID        string
	RegimenID string
	Refill    int64
	Time      int64
	Amount    float64
	Unit      string
}

func (q *Queries) CreateDose(ctx context.Context, arg CreateDoseParams) (Dose, error) {
	row := q.db.QueryRowContext(ctx, createDose,
		arg.ID,
		arg.RegimenID,
		arg.Refill,
		arg.Time,
		arg.Amount,
		arg.Unit,
	)
	var i Dose
	err := row.Scan(
		&i.ID,
		&i.RegimenID,
		&i.Refill,
		&i.Time,
		&i.Amount,
		&i.Unit,
		&i.Taken,
		&i.TimeTaken,
	)
	return i, err
}

const createMedication = `-- name: CreateMedication :one
INSERT INTO
    medications (id, name, generic, brand)
VALUES
    (?, ?, ?, ?) RETURNING id, name, generic, brand
`

type CreateMedicationParams struct {
	ID      string
	Name    string
	Generic bool
	Brand   string
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.db.QueryRowContext(ctx, createMedication,
		arg.ID,
		arg.Name,
		arg.Generic,
		arg.Brand,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Generic,
		&i.Brand,
	)
	return i, err
}

const createRegimen = `-- name: CreateRegimen :one
INSERT INTO
    regimens (id, medication_id, patient, prescription_id)
VALUES
    (?, ?, ?, ?) RETURNING id, medication_id, patient, prescription_id
`

type CreateRegimenParams struct {
	ID             string
	MedicationID   string
	Patient        string
	PrescriptionID string
}

func (q *Queries) CreateRegimen(ctx context.Context, arg CreateRegimenParams) (Regimen, error) {
	row := q.db.QueryRowContext(ctx, createRegimen,
		arg.ID,
		arg.MedicationID,
		arg.Patient,
		arg.PrescriptionID,
	)
	var i Regimen
	err := row.Scan(
		&i.ID,
		&i.MedicationID,
		&i.Patient,
		&i.PrescriptionID,
	)
	return i, err
}

const createRx = `-- name: CreateRx :one
INSERT INTO
    prescriptions (
        id,
        medication_id,
        scheduled_start,
        refills,
        doses,
        schedule,
        patient
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?) RETURNING id, medication_id, schedule, scheduled_start, refills, doses, patient
`

type CreateRxParams struct {
	ID             string
	MedicationID   string
	ScheduledStart sql.NullInt64
	Refills        int64
	Doses          int64
	Schedule       []byte
	Patient        string
}

func (q *Queries) CreateRx(ctx context.Context, arg CreateRxParams) (Prescription, error) {
	row := q.db.QueryRowContext(ctx, createRx,
		arg.ID,
		arg.MedicationID,
		arg.ScheduledStart,
		arg.Refills,
		arg.Doses,
		arg.Schedule,
		arg.Patient,
	)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.MedicationID,
		&i.Schedule,
		&i.ScheduledStart,
		&i.Refills,
		&i.Doses,
		&i.Patient,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (id, approved)
VALUES
    (?, false) RETURNING id, approved
`

func (q *Queries) CreateUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Approved)
	return i, err
}

const dosesTillEmpty = `-- name: DosesTillEmpty :one
SELECT
    count(*)
FROM
    doses
WHERE
    doses.regimen_id = ?
    AND doses.taken IS NULL
`

func (q *Queries) DosesTillEmpty(ctx context.Context, regimenID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, dosesTillEmpty, regimenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dosesTillRefill = `-- name: DosesTillRefill :one
SELECT
    COUNT(*)
FROM
    doses
WHERE
    doses.regimen_id = ?
    AND doses.taken IS NULL
    AND doses.refill = (
        SELECT
            MIN(dose_inner.refill)
        FROM
            doses AS dose_inner
        WHERE
            dose_inner.regimen_id = ?
            AND dose_inner.taken IS NULL
    )
`

type DosesTillRefillParams struct {
	RegimenID   string
	RegimenID_2 string
}

func (q *Queries) DosesTillRefill(ctx context.Context, arg DosesTillRefillParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dosesTillRefill, arg.RegimenID, arg.RegimenID_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDosesByPatient = `-- name: GetDosesByPatient :many
SELECT
    doses.id, doses.regimen_id, doses.refill, doses.time, doses.amount, doses.unit, doses.taken, doses.time_taken,
    medications.id, medications.name, medications.generic, medications.brand,
    regimens.id, regimens.medication_id, regimens.patient, regimens.prescription_id
FROM
    doses
    INNER JOIN regimens ON doses.regimen_id = regimens.id
    INNER JOIN medications ON regimens.medication_id = medications.id
WHERE
    doses.taken IS NULL
    AND regimens.patient = ?
ORDER BY
    doses.Time
`

type GetDosesByPatientRow struct {
	ID             string
	RegimenID      string
	Refill         int64
	Time           int64
	Amount         float64
	Unit           string
	Taken          sql.NullBool
	TimeTaken      sql.NullInt64
	ID_2           string
	Name           string
	Generic        bool
	Brand          string
	ID_3           string
	MedicationID   string
	Patient        string
	PrescriptionID string
}

func (q *Queries) GetDosesByPatient(ctx context.Context, patient string) ([]GetDosesByPatientRow, error) {
	rows, err := q.db.QueryContext(ctx, getDosesByPatient, patient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDosesByPatientRow
	for rows.Next() {
		var i GetDosesByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.RegimenID,
			&i.Refill,
			&i.Time,
			&i.Amount,
			&i.Unit,
			&i.Taken,
			&i.TimeTaken,
			&i.ID_2,
			&i.Name,
			&i.Generic,
			&i.Brand,
			&i.ID_3,
			&i.MedicationID,
			&i.Patient,
			&i.PrescriptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDosesByPatientLimitBy = `-- name: GetDosesByPatientLimitBy :many
SELECT
    doses.id, doses.regimen_id, doses.refill, doses.time, doses.amount, doses.unit, doses.taken, doses.time_taken,
    medications.id, medications.name, medications.generic, medications.brand,
    regimens.id, regimens.medication_id, regimens.patient, regimens.prescription_id
FROM
    doses
    INNER JOIN regimens ON doses.regimen_id = regimens.id
    INNER JOIN medications ON regimens.medication_id = medications.id
WHERE
    doses.taken IS NULL
    AND regimens.patient = ?
ORDER BY
    doses.Time
LIMIT
    ?
`

type GetDosesByPatientLimitByParams struct {
	Patient string
	Limit   int64
}

type GetDosesByPatientLimitByRow struct {
	ID             string
	RegimenID      string
	Refill         int64
	Time           int64
	Amount         float64
	Unit           string
	Taken          sql.NullBool
	TimeTaken      sql.NullInt64
	ID_2           string
	Name           string
	Generic        bool
	Brand          string
	ID_3           string
	MedicationID   string
	Patient        string
	PrescriptionID string
}

func (q *Queries) GetDosesByPatientLimitBy(ctx context.Context, arg GetDosesByPatientLimitByParams) ([]GetDosesByPatientLimitByRow, error) {
	rows, err := q.db.QueryContext(ctx, getDosesByPatientLimitBy, arg.Patient, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDosesByPatientLimitByRow
	for rows.Next() {
		var i GetDosesByPatientLimitByRow
		if err := rows.Scan(
			&i.ID,
			&i.RegimenID,
			&i.Refill,
			&i.Time,
			&i.Amount,
			&i.Unit,
			&i.Taken,
			&i.TimeTaken,
			&i.ID_2,
			&i.Name,
			&i.Generic,
			&i.Brand,
			&i.ID_3,
			&i.MedicationID,
			&i.Patient,
			&i.PrescriptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMedication = `-- name: GetMedication :one
SELECT
    id, name, generic, brand
FROM
    medications
WHERE
    id = ?
`

func (q *Queries) GetMedication(ctx context.Context, id string) (Medication, error) {
	row := q.db.QueryRowContext(ctx, getMedication, id)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Generic,
		&i.Brand,
	)
	return i, err
}

const getRx = `-- name: GetRx :one
SELECT
    id, medication_id, schedule, scheduled_start, refills, doses, patient
FROM
    prescriptions
WHERE
    id = ?
`

func (q *Queries) GetRx(ctx context.Context, id string) (Prescription, error) {
	row := q.db.QueryRowContext(ctx, getRx, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.MedicationID,
		&i.Schedule,
		&i.ScheduledStart,
		&i.Refills,
		&i.Doses,
		&i.Patient,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id, approved
FROM
    users
WHERE
    id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Approved)
	return i, err
}

const markDoseTaken = `-- name: MarkDoseTaken :exec
UPDATE doses
SET
    taken = ?,
    time_taken = ?
WHERE
    id = ?
`

type MarkDoseTakenParams struct {
	Taken     sql.NullBool
	TimeTaken sql.NullInt64
	ID        string
}

func (q *Queries) MarkDoseTaken(ctx context.Context, arg MarkDoseTakenParams) error {
	_, err := q.db.ExecContext(ctx, markDoseTaken, arg.Taken, arg.TimeTaken, arg.ID)
	return err
}
